/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import backend.dao.implementation.JsonVehicleDaoImpl;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.VehicleTableModel;
import pojo.Vehicle;
import view.panels.PnlVisualizacionVehicle;
import view.panels.controllers.PnlVisualizacionVehicleController;

/**
 *
 * @author UZIEL
 */
public class IFrmVehicle extends javax.swing.JInternalFrame
{
    private PnlVisualizacionVehicle pnlVisualizacionVehicle;
    private PnlVisualizacionVehicleController pnlVisualizacionVehicleController;
    /**
     * Creates new form IFrmVehicle
     */
    public IFrmVehicle()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vehicle Catalog");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlVisualizacionVehicle = new PnlVisualizacionVehicle();
        pnlVisualizacionVehicleController = new PnlVisualizacionVehicleController(pnlVisualizacionVehicle);

        pnlContent.add(pnlVisualizacionVehicle, BorderLayout.CENTER);
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed
        DlgVehicle dlgVehicle = new DlgVehicle(null, true);
        dlgVehicle.addPropertySupport(pnlVisualizacionVehicleController.getTblViewModel());
        dlgVehicle.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        int row = pnlVisualizacionVehicle.getTblVisualizacionVehicle().getSelectedRow();
        if(row == -1)
        { 
            JOptionPane.showMessageDialog(null, "Seleccione una fila si desea editar sus campos.",
                    "Updating message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DlgVehicle dlgVehicle = new DlgVehicle(null, true);
        dlgVehicle.loadPnlVehicleData(pnlVisualizacionVehicle, row);
        dlgVehicle.addPropertySupport(pnlVisualizacionVehicleController.getTblViewModel());
        
        dlgVehicle.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        int row = pnlVisualizacionVehicle.getTblVisualizacionVehicle().getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila si desea eliminarla.",
                    "Delete message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this row?","Delete", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.NO_OPTION)
            return;
        
        int vehicleId = (int) pnlVisualizacionVehicle.getTblVisualizacionVehicle().getValueAt(pnlVisualizacionVehicle.getTblVisualizacionVehicle().getSelectedRow(), 14);

        Vehicle vehicle = new Vehicle();
        vehicle.setId(vehicleId);
        JsonVehicleDaoImpl jsonVehicleDaoImpl;
        try
        {
            jsonVehicleDaoImpl = new JsonVehicleDaoImpl();
            jsonVehicleDaoImpl.delete(vehicle);
            
            //VehicleTableModel dtm =  (VehicleTableModel) pnlVisualizacionVehicle.getTblVisualizacionVehicle().getModel(); 
            //dtm.removeRow(row);
            Vehicle v = null;
            pnlVisualizacionVehicleController.getTblViewModel().propertyChange(new PropertyChangeEvent(new Object(), "vehicle", v, vehicle));
            
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(IFrmVehicle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(IFrmVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
