/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.PnlCalculadoraController;
import controllers.PnlTemperaturaController;
import java.awt.BorderLayout;
import javax.swing.JComponent;
import panels.PnlCalculadora;
import panels.PnlTemperatura;

/**
 *
 * @author UZIEL
 */
public class App extends javax.swing.JFrame
{
    PnlCalculadora pnlCalculadora;
    PnlCalculadoraController pnlCalculadoraController;
    
    PnlTemperatura pnlTemperatura;
    PnlTemperaturaController pnlTemperaturaController;
    /**
     * Creates new form App
     */
    public App()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnCalculadora = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 3, 2));

        btnCalculadora.setBackground(new java.awt.Color(204, 204, 204));
        btnCalculadora.setText("Sumar");
        btnCalculadora.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalculadoraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculadora);

        btnTemperatura.setText("Convertir temperatura");
        btnTemperatura.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTemperatura);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(507, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTemperaturaActionPerformed
    {//GEN-HEADEREND:event_btnTemperaturaActionPerformed
        if(pnlTemperatura == null)
        {
            pnlTemperatura = new PnlTemperatura();
            pnlTemperaturaController = new PnlTemperaturaController(pnlTemperatura);
        }
        addComponent(pnlTemperatura);
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalculadoraActionPerformed
    {//GEN-HEADEREND:event_btnCalculadoraActionPerformed
        if(pnlCalculadora == null)
        {
            pnlCalculadora = new PnlCalculadora();
            pnlCalculadoraController = new PnlCalculadoraController(pnlCalculadora);
        }
        addComponent(pnlCalculadora);
    }//GEN-LAST:event_btnCalculadoraActionPerformed

    private void addComponent(JComponent component)
    {
        pnlContent.removeAll();
        pnlContent.add(component, BorderLayout.CENTER);
        pnlContent.repaint();
        this.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
